### ISSUE TITLE
CRI-O and kubectl version mismatch on Kubernetes 1.33

### ISSUE THREAD

**Issue by iholder101** [kubevirt/kubevirtci#1431]
**What happened**:
While trying to work on an implementation for https://github.com/kubevirt/enhancements/pull/46, I've faced errors when trying to in-place resize a pod. This feature-gate is [beta on Kubernetes 1.33](https://github.com/kubernetes/enhancements/blob/a55eefc6051d6684d8cc7521e1f4de6319625e23/keps/sig-node/1287-in-place-update-pod-resources/kep.yaml#L40) and is on by default.

Firstly, I've suspected that this is due to a kubectl mismatch:
```
> k version
selecting docker as container runtime
Client Version: v1.32.3
Kustomize Version: v5.5.0
Server Version: v1.33.0-beta.0
```

So I've downloaded a fresh kubectl instead:
```
> ./kubectl --kubeconfig=./kubevirtci/_ci-configs/k8s-1.33/.kubeconfig version
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.33.0-beta.0
```

But that still didn't help.
Then, I've inspected CRIO's version on the node:
```
> ./kubevirt/kubevirtci/cluster-up/ssh.sh node02
selecting docker as container runtime
[vagrant@node02 ~]$ 
[vagrant@node02 ~]$ sudo su
[root@node02 vagrant]# crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.32.1
RuntimeApiVersion:  v1
```

It seems that the CRIO version is also configured for k8s 1.32 instead of 1.33.

**What you expected to happen**:
CRIO and kubectl to match the 1.33 version, and for in-place pod resize to work.

**How to reproduce it (as minimally and precisely as possible)**:

Create a test pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: my-container
      image: busybox
      command: ["sh", "-c", "echo Hello; sleep 3600"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
```

Patch the pod for resize:
```shell
kubectl patch pod test-pod \
  --type=merge \
  --subresource=resize \
  -p '{
    "spec": {
      "containers": [{
        "name": "my-container",
        "resources": {
          "requests": {
            "cpu": "200m",
            "memory": "256Mi"
          },
          "limits": {
            "cpu": "400m",
            "memory": "512Mi"
          }
        }
      }]
    }
  }'
```

Receive the following error:
```
Error from server (NotFound): the server could not find the requested resource
```

**Additional context**:
As a side-note, `./kubevirtci/_ci-configs/k8s-1.33/.kubectl` did not have execute permissions. I've fixed that with `chmod +x`, but perhaps that's also needs to be fixed.

**Environment**:
- KubeVirt version (use `virtctl version`): main, pre v1.6
- Kubernetes version (use `kubectl version`): 1.33
- OS (e.g. from /etc/os-release): Fedora 41
- Kernel (e.g. `uname -a`): `Linux dc5d2f802447 6.11.9-100.fc39.x86_64`
