### ISSUE TITLE
cloudInitNoCloud userData broken in alpine-with-test-tooling

### ISSUE THREAD

**Issue by akalenyu** [kubevirt/kubevirtci#874]
```yaml
[root@akalenyu kubevirt]# cat ~/manifests/alpine-broken-cloudinit-vm.yaml 
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: alpine-test-tooling-cloudinit
spec:
  running: true
  template:
    metadata:
      labels: {kubevirt.io/domain: alpine-test-tooling-cloudinit,
        kubevirt.io/vm: alpine-test-tooling-cloudinit}
    spec:
      domain:
        devices:
          disks:
          - disk: {bus: virtio}
            name: disk0
          - disk: {bus: virtio}
            name: cloudinitdisk
        resources:
          requests: {memory: 512Mi}
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/alpine-with-test-tooling-container-disk:v0.57.0
          imagePullPolicy: IfNotPresent
        name: disk0
      - cloudInitNoCloud:
          userData: |
            #!/bin/sh
            set -ex

            echo 'HELLO printed from cloud-init userdata'
            touch /root/bar.txt
        name: cloudinitdisk
```

Results in:
```bash
alpine-test-tooling-cloudinit:~# cat /root/bar.txt
cat: can't open '/root/bar.txt': No such file or directory
alpine-test-tooling-cloudinit:~# cat /var/log/cloud-init-output.log 
Cloud-init v. 22.2 running 'init' at Mon, 12 Sep 2022 18:42:50 +0000. Up 7.13 seconds.
ci-info: ++++++++++++++++++++++++Net device info++++++++++++++++++++++++
ci-info: +--------+-------+---------+------+-------+-------------------+
ci-info: | Device |   Up  | Address | Mask | Scope |     Hw-Address    |
ci-info: +--------+-------+---------+------+-------+-------------------+
ci-info: |  eth0  | False |    .    |  .   |   .   | 32:72:fd:b5:be:2e |
ci-info: |   lo   | False |    .    |  .   |   .   |         .         |
ci-info: +--------+-------+---------+------+-------+-------------------+
ci-info: 
2022-09-12 18:42:50,887 - __init__.py[ERROR]: Could not import DataSourceVMware. Does the DataSource exist and is it importable?
2022-09-12 18:42:52,303 - activators.py[WARNING]: Running ['ifup', 'eth0'] resulted in stderr output: udhcpc: started, v1.35.0
```
